export const CURRICULUM = {
  7: {
    title: "Year 7",
    themes: [
      {
        id: "y7-sep",
        period: "September",
        british: {
          title: "What is History and why does it matter?",
          enquiry: "How do we know what we know about the past?",
          topics: ["Historical sources", "Evidence and inference", "Chronology and periodisation"],
          skills: ["Source analysis", "Chronological reasoning", "Historical questioning"],
          knowledge: ["Types of historical sources", "Primary vs secondary sources", "BCE/CE dating"],
          assessment: "Source analysis exercise",
          concepts: ["Evidence", "Causation"],
          vocab: { en: ["source", "evidence", "chronology", "inference"], it: ["fonte", "evidenza", "cronologia", "deduzione"] },
          access: "Illustrated timeline activity",
          stretch: "Evaluate conflicting sources on the same event",
        },
        italian: {
          title: "Cosa è la Storia e perché è importante?",
          enquiry: "Come sappiamo quello che sappiamo del passato?",
          topics: ["Le fonti storiche", "Prove e deduzione", "Cronologia e periodizzazione"],
          skills: ["Analisi delle fonti", "Ragionamento cronologico", "Domande storiche"],
          knowledge: ["Tipi di fonti storiche", "Fonti primarie e secondarie", "Datazione a.C./d.C."],
          assessment: "Esercizio di analisi delle fonti",
          concepts: ["Evidenza", "Causalità"],
          vocab: { en: ["source", "evidence", "chronology"], it: ["fonte", "evidenza", "cronologia"] },
          access: "Attività con linea del tempo illustrata",
          stretch: "Valutare fonti contrastanti sullo stesso evento",
        },
        crossStream: "Both streams begin with the same epistemological questions about History as a discipline.",
        bridgeEnquiry: "How do historians in different countries construct national narratives from the same evidence?",
        bridgeConcept: "Evidence",
      },
      {
        id: "y7-oct",
        period: "October",
        british: {
          title: "Roman Britain",
          enquiry: "How did Roman rule transform Britain?",
          topics: ["Roman invasion and conquest", "Romanisation of Britain", "End of Roman rule"],
          skills: ["Causation analysis", "Change and continuity", "Archaeological evidence"],
          knowledge: ["Julius Caesar's expeditions", "Claudian invasion 43AD", "Hadrian's Wall", "Roman towns and roads"],
          assessment: "Change and continuity essay",
          concepts: ["Change", "Empire"],
          vocab: { en: ["conquest", "empire", "romanisation", "legacy"], it: ["conquista", "impero", "romanizzazione", "eredità"] },
          access: "Roman Britain map activity",
          stretch: "Assess the long-term legacy of Roman rule in Britain",
        },
        italian: {
          title: "Roma antica — la città e il suo mondo",
          enquiry: "Come Roma trasformò il mondo mediterraneo?",
          topics: ["L'espansione di Roma", "La società romana", "L'eredità di Roma"],
          skills: ["Analisi della causalità", "Cambiamento e continuità", "Prove archeologiche"],
          knowledge: ["La Repubblica e l'Impero", "L'esercito romano", "La via Appia", "Pompei"],
          assessment: "Saggio su cambiamento e continuità",
          concepts: ["Cambiamento", "Impero"],
          vocab: { en: ["senate", "republic", "legion", "forum"], it: ["senato", "repubblica", "legione", "foro"] },
          access: "Attività cartografica sull'espansione romana",
          stretch: "Confrontare l'eredità di Roma in Italia e in Britannia",
        },
        crossStream: "Both streams study Roman civilisation but from geographically different perspectives — Britain as a province, Italy as the core.",
        bridgeEnquiry: "Was the Roman Empire experienced differently at its centre and its edges?",
        bridgeConcept: "Empire",
      },
      {
        id: "y7-nov",
        period: "November",
        british: {
          title: "The Norman Conquest and Medieval England",
          enquiry: "How did 1066 change England forever?",
          topics: ["The Norman Conquest", "Feudal system", "The Church in medieval England"],
          skills: ["Significance judgement", "Source analysis (Bayeux Tapestry)", "Consequence mapping"],
          knowledge: ["Battle of Hastings 1066", "William I and Domesday Book", "Norman castles and cathedrals", "Feudal hierarchy"],
          assessment: "Significance essay: Why was 1066 a turning point?",
          concepts: ["Power", "Feudalism"],
          vocab: { en: ["feudalism", "vassal", "domesday", "conquest", "sovereignty"], it: ["feudalesimo", "vassallo", "catasto", "conquista", "sovranità"] },
          access: "Feudal pyramid diagram activity",
          stretch: "Compare the Norman impact on England with later colonial conquests",
        },
        italian: {
          title: "Il Medioevo — potere, terra e fede",
          enquiry: "Chi controllava davvero l'Europa medievale — il papa o i re?",
          topics: ["Il sistema feudale in Italia", "La lotta per le investiture", "I Comuni italiani"],
          skills: ["Giudizio di significato", "Analisi delle fonti", "Mappatura delle conseguenze"],
          knowledge: ["Federico Barbarossa e i Comuni", "La lotta per le investiture (Enrico IV e Gregorio VII)", "Il Sacro Romano Impero", "I liberi Comuni"],
          assessment: "Saggio: La lotta per le investiture — chi vinse davvero?",
          concepts: ["Potere", "Feudalesimo"],
          vocab: { en: ["investiture", "commune", "emperor", "pope"], it: ["investitura", "comune", "imperatore", "papa"] },
          access: "Diagramma della gerarchia feudale",
          stretch: "Confrontare il feudalesimo normanno con il sistema dei Comuni italiani",
        },
        crossStream: "Both streams examine how power was structured and contested in medieval Europe — through land in England, through city-states and Church conflicts in Italy.",
        bridgeEnquiry: "Was medieval power really about land, faith, or something else entirely?",
        bridgeConcept: "Power & Land & Faith",
      },
      {
        id: "y7-decjan",
        period: "December / January",
        british: {
          title: "The Crusades",
          enquiry: "Were the Crusades about faith, power, or greed?",
          topics: ["Causes of the Crusades", "The First Crusade", "Muslim perspectives", "Long-term consequences"],
          skills: ["Multi-causal analysis", "Perspective-taking", "Significance"],
          knowledge: ["Pope Urban II's call 1095", "The People's Crusade", "Saladin and the Third Crusade", "Impact on trade and culture"],
          assessment: "Multi-perspective essay on the Crusades",
          concepts: ["Religion", "Conflict", "Encounter"],
          vocab: { en: ["crusade", "pilgrimage", "jihad", "reconquista", "crusader"], it: ["crociata", "pellegrinaggio", "jihad", "reconquista", "crociato"] },
          access: "Map of Crusade routes",
          stretch: "Evaluate how historians from different backgrounds interpret the Crusades",
        },
        italian: {
          title: "Le Crociate — fede, potere o avidità?",
          enquiry: "Le Crociate furono una guerra santa o una conquista economica?",
          topics: ["Le cause delle Crociate", "Il ruolo di Venezia e Genova", "Le prospettive islamiche", "Conseguenze a lungo termine"],
          skills: ["Analisi multicausale", "Prospettiva storica", "Significato"],
          knowledge: ["Papa Urbano II 1095", "La Quarta Crociata e il sacco di Costantinopoli", "Saladino", "Il ruolo delle città-stato italiane nel commercio crociato"],
          assessment: "Saggio multi-prospettico sulle Crociate",
          concepts: ["Religione", "Conflitto", "Incontro"],
          vocab: { en: ["crusade", "Venice", "Constantinople", "trade"], it: ["crociata", "Venezia", "Costantinopoli", "commercio"] },
          access: "Carta delle rotte delle Crociate",
          stretch: "Analizzare come le città-stato italiane usarono le Crociate per espandere il proprio potere commerciale",
        },
        crossStream: "Both streams study the same events but the Italian stream foregrounds the commercial interests of Italian city-states, adding economic motivation alongside faith.",
        bridgeEnquiry: "Can the same historical event be simultaneously a religious war and a commercial opportunity?",
        bridgeConcept: "Encounter",
      },
      {
        id: "y7-febmar",
        period: "February / March",
        british: {
          title: "The Black Death and its Consequences",
          enquiry: "Did the Black Death create the conditions for a more equal society?",
          topics: ["Causes and spread of the Black Death", "Social impact", "The Peasants' Revolt 1381"],
          skills: ["Causation and consequence", "Change over time", "Statistical evidence"],
          knowledge: ["Spread from Central Asia", "Death toll estimates", "Flagellants and Jewish persecution", "Wat Tyler and the Peasants' Revolt"],
          assessment: "Structured essay: consequences of the Black Death",
          concepts: ["Change", "Society"],
          vocab: { en: ["plague", "mortality", "serfdom", "revolt", "consequence"], it: ["peste", "mortalità", "servitù della gleba", "rivolta", "conseguenza"] },
          access: "Consequence diagram",
          stretch: "Argue whether the Black Death was ultimately positive or negative for English society",
        },
        italian: {
          title: "La Peste Nera e la fine del Medioevo",
          enquiry: "Come la Peste Nera cambiò per sempre la società italiana?",
          topics: ["La diffusione della Peste Nera in Italia", "L'impatto sulla società e l'arte", "Il Decameron di Boccaccio"],
          skills: ["Causalità e conseguenza", "Cambiamento nel tempo", "Fonti letterarie come evidenza storica"],
          knowledge: ["L'arrivo della peste in Sicilia 1347", "La mortalità nelle città italiane", "La risposta degli artisti e degli scrittori", "L'impatto sul commercio"],
          assessment: "Saggio strutturato: le conseguenze della Peste Nera in Italia",
          concepts: ["Cambiamento", "Società"],
          vocab: { en: ["plague", "mortality", "Decameron", "art"], it: ["peste", "mortalità", "Decameron", "arte"] },
          access: "Diagramma delle conseguenze",
          stretch: "Usare il Decameron come fonte storica — cosa ci dice sulla società del Trecento?",
        },
        crossStream: "Both streams experience the same catastrophe but examine it through different cultural lenses — English social upheaval vs Italian literary and artistic response.",
        bridgeEnquiry: "How did a shared catastrophe produce such different cultural responses in England and Italy?",
        bridgeConcept: "Change",
      },
      {
        id: "y7-apr",
        period: "April",
        british: {
          title: "The Renaissance",
          enquiry: "Was the Renaissance a revolution in human thought?",
          topics: ["Origins of the Renaissance in Italy", "Humanism", "Renaissance art and science", "Impact on England"],
          skills: ["Significance", "Continuity and change", "Cultural analysis"],
          knowledge: ["Italian city-states as centres of Renaissance", "Leonardo da Vinci", "Gutenberg's printing press", "Thomas More and English humanism"],
          assessment: "Essay: Was the Renaissance truly revolutionary?",
          concepts: ["Ideas", "Progress"],
          vocab: { en: ["renaissance", "humanism", "patronage", "perspective"], it: ["rinascimento", "umanesimo", "mecenatismo", "prospettiva"] },
          access: "Art analysis activity",
          stretch: "Evaluate how 'revolutionary' the Renaissance really was compared to earlier periods",
        },
        italian: {
          title: "Il Rinascimento — un'epoca nuova",
          enquiry: "Il Rinascimento era davvero una 'rinascita' o qualcosa di completamente nuovo?",
          topics: ["Le origini del Rinascimento in Toscana", "L'umanesimo e la nuova visione dell'uomo", "Arte e scienza nel Rinascimento", "I Medici e il mecenatismo"],
          skills: ["Significato", "Continuità e cambiamento", "Analisi culturale"],
          knowledge: ["Firenze come centro del Rinascimento", "Leonardo da Vinci, Michelangelo, Botticelli", "I Medici", "Dante, Petrarca, Boccaccio"],
          assessment: "Saggio: Il Rinascimento fu davvero rivoluzionario?",
          concepts: ["Idee", "Progresso"],
          vocab: { en: ["renaissance", "Florence", "Medici", "patronage"], it: ["rinascimento", "Firenze", "Medici", "mecenatismo"] },
          access: "Attività di analisi artistica",
          stretch: "Confrontare il Rinascimento italiano con la sua ricezione in Inghilterra: cosa si perse nella traduzione culturale?",
        },
        crossStream: "The Renaissance originates in Italian city-states — the Italian stream studies it from the inside while the British stream examines how Italian ideas transformed England.",
        bridgeEnquiry: "When ideas travel across borders, do they change? What did England gain — and lose — from the Italian Renaissance?",
        bridgeConcept: "Ideas",
      },
      {
        id: "y7-may",
        period: "May",
        british: {
          title: "The Reformation",
          enquiry: "Was the English Reformation driven by faith or by politics?",
          topics: ["Martin Luther and the European Reformation", "Henry VIII and the break with Rome", "Religious change under Edward, Mary, Elizabeth"],
          skills: ["Causation", "Significance", "Interpretations"],
          knowledge: ["Luther's 95 Theses 1517", "Henry VIII's divorce crisis", "Dissolution of the Monasteries", "Elizabethan Settlement"],
          assessment: "Source-based assessment on the causes of the English Reformation",
          concepts: ["Religion", "Power"],
          vocab: { en: ["reformation", "protestant", "catholic", "schism", "dissolution"], it: ["riforma", "protestante", "cattolico", "scisma", "dissoluzione"] },
          access: "Cause and consequence card sort",
          stretch: "Was the English Reformation truly religious or essentially political? Build the case for both.",
        },
        italian: {
          title: "La Riforma e la Controriforma",
          enquiry: "La Controriforma salvò o trasformò la Chiesa cattolica?",
          topics: ["Lutero e la Riforma protestante", "Il Concilio di Trento", "La Controriforma in Italia", "L'Inquisizione"],
          skills: ["Causalità", "Significato", "Interpretazioni"],
          knowledge: ["Le 95 Tesi di Lutero", "Carlo V e i principi protestanti", "Il Concilio di Trento 1545-63", "Ignazio di Loyola e i Gesuiti"],
          assessment: "Valutazione basata su fonti sulle cause della Riforma in Europa",
          concepts: ["Religione", "Potere"],
          vocab: { en: ["counter-reformation", "Council of Trent", "Inquisition", "Jesuit"], it: ["controriforma", "Concilio di Trento", "Inquisizione", "Gesuita"] },
          access: "Ordinamento di carte su causa e conseguenza",
          stretch: "Il Concilio di Trento rappresentò un successo o un fallimento per la Chiesa cattolica?",
        },
        crossStream: "England breaks from Rome while Italy becomes the centre of the Counter-Reformation — the same religious earthquake produces opposite institutional responses.",
        bridgeEnquiry: "How can the same crisis — the Reformation — produce such different outcomes in England and Italy?",
        bridgeConcept: "Religion",
      },
      {
        id: "y7-jun",
        period: "June",
        british: {
          title: "Elizabethan England",
          enquiry: "Was Elizabeth I's reign truly a 'Golden Age'?",
          topics: ["The Elizabethan Settlement", "Mary Queen of Scots", "The Spanish Armada", "Elizabethan culture"],
          skills: ["Interpretations", "Significance", "Evidence evaluation"],
          knowledge: ["Elizabeth I's reign 1558-1603", "The Armada 1588", "Shakespeare and Elizabethan theatre", "Exploration and empire-building"],
          assessment: "End-of-year extended essay: Was Elizabethan England a 'Golden Age'?",
          concepts: ["Power", "Identity"],
          vocab: { en: ["armada", "patronage", "settlement", "sovereignty", "propaganda"], it: ["armata", "mecenatismo", "accordo", "sovranità", "propaganda"] },
          access: "Structured essay scaffold",
          stretch: "For whom was Elizabethan England a Golden Age? Was it experienced equally by all?",
        },
        italian: {
          title: "L'Italia nel Cinquecento — tra grandezza e crisi",
          enquiry: "Il Cinquecento fu un'epoca d'oro o di declino per l'Italia?",
          topics: ["Le guerre d'Italia", "Il Sacco di Roma 1527", "L'Italia sotto dominazione straniera", "La cultura italiana nel Cinquecento"],
          skills: ["Interpretazioni", "Significato", "Valutazione dell'evidenza"],
          knowledge: ["Carlo V e le guerre d'Italia", "Il Sacco di Roma", "Venezia come potenza indipendente", "Machiavelli e il Principe"],
          assessment: "Saggio di fine anno: Il Cinquecento fu un'epoca d'oro o di declino per l'Italia?",
          concepts: ["Potere", "Identità"],
          vocab: { en: ["sack", "foreign domination", "Machiavelli", "city-state"], it: ["sacco", "dominazione straniera", "Machiavelli", "città-stato"] },
          access: "Struttura per saggio guidato",
          stretch: "Confrontare il concetto di 'età dell'oro' nelle due culture: chi definisce cosa è 'dorato'?",
        },
        crossStream: "Both streams end Year 7 with a moment of national reckoning — England at its confident Elizabethan peak, Italy under foreign domination. A powerful contrast for reflection.",
        bridgeEnquiry: "Can two countries experience the same century so differently? What does 'national success' mean in history?",
        bridgeConcept: "Identity",
      },
    ],
  },
  8: {
    title: "Year 8",
    themes: [
      {
        id: "y8-sep",
        period: "September",
        british: {
          title: "Stuart England and the English Civil War",
          enquiry: "Was the execution of Charles I a revolution or a crime?",
          topics: ["The Divine Right of Kings", "Parliament vs Crown", "The Civil War", "The Interregnum and Restoration"],
          skills: ["Causation", "Significance", "Interpretations"],
          knowledge: ["James I and the Gunpowder Plot", "Charles I and the Personal Rule", "Oliver Cromwell and the New Model Army", "The Restoration 1660"],
          assessment: "Source-based essay: Was Charles I's execution justified?",
          concepts: ["Power", "Revolution"],
          vocab: { en: ["divine right", "parliament", "civil war", "regicide", "commonwealth"], it: ["diritto divino", "parlamento", "guerra civile", "regicidio", "repubblica"] },
          access: "Cause card sort",
          stretch: "Compare the English Revolution with later revolutions — is it fair to call it a revolution?",
        },
        italian: {
          title: "L'Italia nel Seicento — barocco e crisi",
          enquiry: "Il Seicento fu un'epoca di crisi o di splendore culturale per l'Italia?",
          topics: ["L'arte barocca in Italia", "La crisi economica e demografica", "Galileo e la Rivoluzione Scientifica", "L'Italia sotto gli Asburgo"],
          skills: ["Causalità", "Significato", "Interpretazioni"],
          knowledge: ["Caravaggio e l'arte barocca", "Galileo Galilei e il processo dell'Inquisizione", "La decadenza delle città-stato italiane", "La Guerra dei Trent'anni e l'Italia"],
          assessment: "Saggio: Il Seicento fu davvero un'epoca di crisi per l'Italia?",
          concepts: ["Potere", "Rivoluzione"],
          vocab: { en: ["baroque", "Galileo", "Inquisition", "scientific revolution"], it: ["barocco", "Galileo", "Inquisizione", "rivoluzione scientifica"] },
          access: "Ordinamento di carte sulla causalità",
          stretch: "Come la censura dell'Inquisizione rallentò il progresso scientifico in Italia?",
        },
        crossStream: "England overthrows its king; Italy experiences political stagnation and cultural baroque splendour. Both grapple with power, legitimacy, and intellectual boundaries.",
        bridgeEnquiry: "In the 17th century, did power shift more fundamentally in England or in Italy — and what counts as a shift?",
        bridgeConcept: "Revolution",
      },
      {
        id: "y8-oct",
        period: "October",
        british: {
          title: "The Transatlantic Slave Trade",
          enquiry: "How was the transatlantic slave trade made possible — and how was it ended?",
          topics: ["The triangular trade", "Life and resistance", "Abolition movement", "Legacy and reparations"],
          skills: ["Empathy and perspective", "Causation", "Significance", "Historical interpretations"],
          knowledge: ["The Middle Passage", "Plantation economy", "Olaudah Equiano", "Wilberforce and the abolition movement", "Abolition Acts 1807 and 1833"],
          assessment: "Essay: Who deserves most credit for the abolition of the slave trade?",
          concepts: ["Slavery", "Resistance", "Justice"],
          vocab: { en: ["triangular trade", "abolition", "emancipation", "resistance", "reparations"], it: ["commercio triangolare", "abolizione", "emancipazione", "resistenza", "riparazioni"] },
          access: "Perspective-taking structured activity",
          stretch: "Evaluate the extent to which British economic interests drove both the slave trade and its abolition",
        },
        italian: {
          title: "La tratta degli schiavi e il colonialismo europeo",
          enquiry: "Come l'Europa giustificò lo schiavismo e il colonialismo?",
          topics: ["La tratta transatlantica degli schiavi", "Il ruolo dell'Italia nel commercio coloniale", "Le giustificazioni ideologiche", "L'eredità del colonialismo"],
          skills: ["Empatia e prospettiva", "Causalità", "Significato"],
          knowledge: ["Il commercio triangolare", "Il ruolo di Genova e Venezia nel commercio pre-coloniale degli schiavi", "Le giustificazioni razziali", "L'abolizione in Europa"],
          assessment: "Saggio: Come l'Europa giustificò lo schiavismo?",
          concepts: ["Schiavitù", "Resistenza", "Giustizia"],
          vocab: { en: ["colonialism", "ideology", "justification", "abolition"], it: ["colonialismo", "ideologia", "giustificazione", "abolizione"] },
          access: "Attività strutturata sulla prospettiva",
          stretch: "Confrontare le diverse forme di schiavitù nella storia europea — che cosa accomuna questi sistemi?",
        },
        crossStream: "A shared moral reckoning: both streams examine how Europe built and justified systems of exploitation, and how they were eventually challenged.",
        bridgeEnquiry: "Whose voices shaped the abolition of slavery — and whose voices were silenced?",
        bridgeConcept: "Justice",
      },
      {
        id: "y8-nov",
        period: "November",
        british: {
          title: "The French Revolution and Napoleon",
          enquiry: "Did the French Revolution make the world better or worse?",
          topics: ["Causes of the French Revolution", "Reign of Terror", "Napoleon — liberator or dictator?", "Impact on Europe"],
          skills: ["Causation and consequence", "Interpretations", "Significance"],
          knowledge: ["Estates General and the Tennis Court Oath", "The Declaration of the Rights of Man", "Robespierre and the Terror", "Napoleon's campaigns and the Napoleonic Code"],
          assessment: "Debate essay: Was Napoleon a force for good?",
          concepts: ["Revolution", "Liberty", "Nationalism"],
          vocab: { en: ["revolution", "liberty", "nationalism", "terror", "empire"], it: ["rivoluzione", "libertà", "nazionalismo", "terrore", "impero"] },
          access: "Cause diagram scaffold",
          stretch: "Argue whether the French Revolution ultimately strengthened or weakened the cause of liberty in Europe",
        },
        italian: {
          title: "La Rivoluzione Francese e Napoleone in Italia",
          enquiry: "Napoleone fu il liberatore dell'Italia o il suo conquistatore?",
          topics: ["La Rivoluzione Francese e le sue idee", "Napoleone in Italia — le campagne", "Le Repubbliche Sorelle", "L'eredità napoleonica in Italia"],
          skills: ["Causalità e conseguenza", "Interpretazioni", "Significato"],
          knowledge: ["Le campagne d'Italia 1796-97", "Le Repubbliche Cisalpina e Partenopea", "Il Codice Napoleonico in Italia", "Il Congresso di Vienna e la Restaurazione"],
          assessment: "Saggio dibattito: Napoleone fu un liberatore o un conquistatore per l'Italia?",
          concepts: ["Rivoluzione", "Libertà", "Nazionalismo"],
          vocab: { en: ["liberation", "republic", "Congress of Vienna", "Restoration"], it: ["liberazione", "repubblica", "Congresso di Vienna", "Restaurazione"] },
          access: "Struttura per diagramma delle cause",
          stretch: "Valutare l'impatto a lungo termine di Napoleone sull'identità italiana e sul Risorgimento",
        },
        crossStream: "Napoleon directly invades and reshapes Italy — the Italian stream experiences French revolutionary ideas as both liberation and occupation. Britain resists from the outside.",
        bridgeEnquiry: "Can the same historical figure be simultaneously a liberator and an oppressor — and does it depend on where you stand?",
        bridgeConcept: "Liberty",
      },
      {
        id: "y8-dec",
        period: "December",
        british: {
          title: "The Industrial Revolution",
          enquiry: "Did the Industrial Revolution improve ordinary people's lives?",
          topics: ["Causes of industrialisation", "Life and work in factories and mines", "Social reform movements", "Impact on the environment"],
          skills: ["Change and continuity", "Evidence evaluation", "Statistical analysis"],
          knowledge: ["Steam engine and textile mills", "Child labour and Factory Acts", "Robert Owen and social reform", "Urbanisation and public health"],
          assessment: "Structured essay: Did industrialisation improve lives?",
          concepts: ["Progress", "Labour", "Environment"],
          vocab: { en: ["industrialisation", "urbanisation", "reform", "labour", "capitalism"], it: ["industrializzazione", "urbanizzazione", "riforma", "lavoro", "capitalismo"] },
          access: "Statistical evidence analysis activity",
          stretch: "Weigh the costs and benefits of industrialisation — who paid the price of progress?",
        },
        italian: {
          title: "L'Italia nell'Ottocento — verso l'unità",
          enquiry: "Il Risorgimento fu una rivoluzione popolare o un progetto d'élite?",
          topics: ["L'Italia dopo il Congresso di Vienna", "Mazzini, Garibaldi e Cavour", "I Mille e l'Unità d'Italia", "I problemi del nuovo stato unito"],
          skills: ["Cambiamento e continuità", "Valutazione dell'evidenza", "Significato"],
          knowledge: ["La Giovine Italia di Mazzini", "Garibaldi e la Spedizione dei Mille 1860", "Cavour e il Piemonte", "La proclamazione del Regno d'Italia 1861"],
          assessment: "Saggio strutturato: Il Risorgimento — rivoluzione dal basso o dall'alto?",
          concepts: ["Progresso", "Nazione", "Identità"],
          vocab: { en: ["Risorgimento", "unification", "nationalism", "Garibaldi"], it: ["Risorgimento", "unificazione", "nazionalismo", "Garibaldi"] },
          access: "Attività di analisi dell'evidenza",
          stretch: "Confrontare il Risorgimento italiano con altri movimenti nazionalisti dell'Ottocento",
        },
        crossStream: "Britain industrialises and debates social progress; Italy unifies and debates what kind of nation it will be. Both are fundamentally about who controls the future.",
        bridgeEnquiry: "In the 19th century, was 'progress' defined by industry or by national identity — and can the same word mean different things to different peoples?",
        bridgeConcept: "Progress",
      },
      {
        id: "y8-jan",
        period: "January",
        british: {
          title: "The British Empire",
          enquiry: "Was the British Empire a force for good or evil in the world?",
          topics: ["How the Empire was built", "India and the Raj", "Resistance and rebellion", "The impact of Empire today"],
          skills: ["Interpretations", "Significance", "Perspective-taking"],
          knowledge: ["East India Company", "The Indian Mutiny/Uprising 1857", "Cecil Rhodes and Africa", "Impact on colonised peoples"],
          assessment: "Essay: Was the British Empire ultimately a force for good?",
          concepts: ["Empire", "Power", "Identity"],
          vocab: { en: ["empire", "colonialism", "resistance", "exploitation", "decolonisation"], it: ["impero", "colonialismo", "resistenza", "sfruttamento", "decolonizzazione"] },
          access: "Perspective-taking structured task",
          stretch: "Evaluate the long-term economic impact of Empire on both Britain and colonised nations",
        },
        italian: {
          title: "Il colonialismo italiano",
          enquiry: "Il colonialismo italiano — ambizione imperiale o avventura fallita?",
          topics: ["Le ragioni del colonialismo italiano", "L'Eritrea, la Somalia e la Libia", "La battaglia di Adua 1896", "L'eredità del colonialismo italiano"],
          skills: ["Interpretazioni", "Significato", "Prospettiva"],
          knowledge: ["I movimenti coloniali italiani fine Ottocento", "La sconfitta di Adua contro l'Etiopia", "La conquista della Libia 1911-12", "Il dibattito sull'eredità coloniale"],
          assessment: "Saggio: Il colonialismo italiano fu un successo o un fallimento?",
          concepts: ["Impero", "Potere", "Identità"],
          vocab: { en: ["Adua", "Libya", "Ethiopia", "colonial legacy"], it: ["Adua", "Libia", "Etiopia", "eredità coloniale"] },
          access: "Compito strutturato sulla prospettiva",
          stretch: "Confrontare il colonialismo italiano con quello britannico — esistono differenze morali o solo differenze di scala?",
        },
        crossStream: "Both countries built empires — Britain a vast global one, Italy a smaller and ultimately less successful one. The contrast illuminates why imperialism appealed to European nations and what it cost.",
        bridgeEnquiry: "Does the scale of an empire determine its moral significance — or is imperialism equally problematic regardless of size?",
        bridgeConcept: "Empire",
      },
      {
        id: "y8-feb",
        period: "February",
        british: {
          title: "World War One",
          enquiry: "Was the First World War inevitable?",
          topics: ["The alliance system and causes of WWI", "Life in the trenches", "The Home Front", "Consequences and the Treaty of Versailles"],
          skills: ["Multi-causal analysis", "Evidence evaluation", "Significance"],
          knowledge: ["The assassination of Franz Ferdinand", "The Schlieffen Plan", "The Battle of the Somme", "The Treaty of Versailles 1919"],
          assessment: "Extended essay: Was the First World War inevitable?",
          concepts: ["War", "Nationalism", "Consequence"],
          vocab: { en: ["alliance", "trench warfare", "armistice", "reparations", "mandate"], it: ["alleanza", "guerra di trincea", "armistizio", "riparazioni", "mandato"] },
          access: "Multi-causal diagram",
          stretch: "Evaluate Fisher's thesis that Germany deliberately caused WWI",
        },
        italian: {
          title: "L'Italia e la Prima Guerra Mondiale",
          enquiry: "L'Italia fece la scelta giusta entrando in guerra nel 1915?",
          topics: ["La neutralità italiana 1914", "Il Patto di Londra 1915", "La guerra in Italia — Caporetto e Vittorio Veneto", "La 'vittoria mutilata' e il dopoguerra"],
          skills: ["Analisi multicausale", "Valutazione dell'evidenza", "Significato"],
          knowledge: ["L'Italia neutrale nel 1914", "Il Patto di Londra", "La disfatta di Caporetto 1917", "La 'vittoria mutilata' — le promesse non mantenute"],
          assessment: "Saggio esteso: L'Italia guadagnò o perse dalla Prima Guerra Mondiale?",
          concepts: ["Guerra", "Nazionalismo", "Conseguenza"],
          vocab: { en: ["neutrality", "Pact of London", "Caporetto", "mutilated victory"], it: ["neutralità", "Patto di Londra", "Caporetto", "vittoria mutilata"] },
          access: "Diagramma multicausale",
          stretch: "Analizzare come la 'vittoria mutilata' aprì la strada al fascismo",
        },
        crossStream: "Britain and Italy fight in the same war but with radically different experiences of it — Britain emerges as a victor, Italy feels cheated of its promised territorial gains.",
        bridgeEnquiry: "Can you win a war and still feel defeated? How does national narrative shape the memory of conflict?",
        bridgeConcept: "War",
      },
      {
        id: "y8-mar",
        period: "March",
        british: {
          title: "The Rise of Fascism and the Road to World War Two",
          enquiry: "Could the Second World War have been prevented?",
          topics: ["The Weimar Republic and its weakness", "Hitler's rise to power", "Appeasement", "Causes of WWII"],
          skills: ["Causation", "Counterfactual thinking", "Significance"],
          knowledge: ["The Great Depression", "Hitler and the Nazi Party", "Chamberlain and Munich 1938", "The invasion of Poland"],
          assessment: "Essay: Could WWII have been prevented?",
          concepts: ["Fascism", "Appeasement", "Causation"],
          vocab: { en: ["fascism", "appeasement", "totalitarianism", "propaganda", "genocide"], it: ["fascismo", "appeasement", "totalitarismo", "propaganda", "genocidio"] },
          access: "Causation card sort",
          stretch: "Evaluate whether appeasement was rational foreign policy or dangerous naivety",
        },
        italian: {
          title: "Il Fascismo in Italia",
          enquiry: "Come Mussolini conquistò il potere — e perché gli italiani lo sostennero?",
          topics: ["La crisi del dopoguerra e i 'bienni'", "Mussolini e il Partito Fascista", "La marcia su Roma 1922", "La dittatura fascista"],
          skills: ["Causalità", "Significato", "Interpretazioni"],
          knowledge: ["Il 'biennio rosso' e il 'biennio nero'", "Mussolini e il movimento fascista", "La marcia su Roma 1922", "La legge Acerbo e la dittatura"],
          assessment: "Saggio: Perché gli italiani sostennero Mussolini?",
          concepts: ["Fascismo", "Dittatura", "Causalità"],
          vocab: { en: ["Mussolini", "March on Rome", "Duce", "squadrismo"], it: ["Mussolini", "marcia su Roma", "Duce", "squadrismo"] },
          access: "Ordinamento di carte sulla causalità",
          stretch: "Confrontare la salita al potere di Mussolini con quella di Hitler — esistono differenze significative?",
        },
        crossStream: "Italy is the birthplace of fascism; Germany imports and radicalises the model. The Italian stream examines fascism from within; the British stream examines appeasement from the outside.",
        bridgeEnquiry: "If fascism was born in Italy and grew in Germany, who bears more responsibility for the catastrophe of WWII?",
        bridgeConcept: "Fascism",
      },
      {
        id: "y8-apr",
        period: "April",
        british: {
          title: "World War Two",
          enquiry: "Was World War Two a 'Good War'?",
          topics: ["Theatres of the war", "The Holocaust", "The Home Front", "The dropping of the atomic bombs"],
          skills: ["Moral reasoning", "Evidence evaluation", "Significance"],
          knowledge: ["Dunkirk", "The Battle of Britain", "The Holocaust and Nazi ideology", "D-Day and VE Day"],
          assessment: "Structured essay: Was WWII a 'Good War'?",
          concepts: ["War", "Justice", "Humanity"],
          vocab: { en: ["holocaust", "genocide", "resistance", "liberation", "atomic bomb"], it: ["olocausto", "genocidio", "resistenza", "liberazione", "bomba atomica"] },
          access: "Moral reasoning framework activity",
          stretch: "Can any war be 'good'? Construct a philosophical argument for and against",
        },
        italian: {
          title: "L'Italia nella Seconda Guerra Mondiale e la Resistenza",
          enquiry: "La Resistenza italiana fu un movimento popolare o un mito fondativo?",
          topics: ["L'Italia in guerra 1940-43", "L'armistizio e l'occupazione tedesca", "La Resistenza partigiana", "La liberazione e il dopoguerra"],
          skills: ["Ragionamento morale", "Valutazione dell'evidenza", "Significato"],
          knowledge: ["L'Italia fascista in guerra", "L'armistizio dell'8 settembre 1943", "La Repubblica Sociale Italiana", "I partigiani e la liberazione"],
          assessment: "Saggio strutturato: La Resistenza italiana — realtà o mito?",
          concepts: ["Guerra", "Giustizia", "Umanità"],
          vocab: { en: ["armistice", "partisan", "liberation", "Republic of Salò"], it: ["armistizio", "partigiano", "liberazione", "Repubblica di Salò"] },
          access: "Struttura per ragionamento morale",
          stretch: "Valutare in che misura la narrativa della Resistenza fu costruita nel dopoguerra per ragioni politiche",
        },
        crossStream: "Britain fights WWII as a continuous defender; Italy changes sides, making the Italian experience of WWII uniquely complex — occupation, collaboration, and resistance all coexist.",
        bridgeEnquiry: "Is a nation that changes sides in war a traitor or a pragmatist — and does it matter which side they ultimately choose?",
        bridgeConcept: "Resistance",
      },
      {
        id: "y8-mayjun",
        period: "May / June",
        british: {
          title: "The Cold War and the Post-War World",
          enquiry: "Did the Cold War make the world more or less dangerous than the hot wars before it?",
          topics: ["Origins of the Cold War", "The arms race and nuclear threat", "Korea, Cuba, Vietnam", "The fall of the Berlin Wall"],
          skills: ["Causation", "Significance", "Interpretations"],
          knowledge: ["The Iron Curtain", "The Marshall Plan", "The Cuban Missile Crisis 1962", "The Berlin Wall 1961-1989"],
          assessment: "End-of-year extended essay: Was the Cold War cold — or just a different kind of hot?",
          concepts: ["Power", "Ideology", "Conflict"],
          vocab: { en: ["cold war", "containment", "détente", "nuclear deterrence", "iron curtain"], it: ["guerra fredda", "contenimento", "distensione", "deterrenza nucleare", "cortina di ferro"] },
          access: "Cause and consequence diagram",
          stretch: "Evaluate whether MAD (Mutually Assured Destruction) actually kept the peace",
        },
        italian: {
          title: "L'Italia nel dopoguerra e la Repubblica",
          enquiry: "Come l'Italia ricostruì la sua identità democratica dopo il fascismo?",
          topics: ["La nascita della Repubblica 1946", "Il miracolo economico italiano", "Il terrorismo degli anni di piombo", "L'Italia nell'Europa e nella NATO"],
          skills: ["Causalità", "Significato", "Interpretazioni"],
          knowledge: ["Il referendum del 2 giugno 1946", "La Costituzione italiana", "Il miracolo economico degli anni '50 e '60", "Le Brigate Rosse e gli anni di piombo"],
          assessment: "Saggio esteso di fine anno: L'Italia divenne davvero una democrazia dopo il 1946?",
          concepts: ["Potere", "Ideologia", "Identità"],
          vocab: { en: ["republic", "constitution", "economic miracle", "terrorism"], it: ["repubblica", "costituzione", "miracolo economico", "terrorismo"] },
          access: "Diagramma di causa e conseguenza",
          stretch: "Confrontare la transizione democratica italiana con quella di altri paesi europei dopo il fascismo",
        },
        crossStream: "Britain's post-war story is of global retrenchment and welfare state building; Italy's is of democratic reconstruction and economic rebirth. Both face the Cold War from different starting points.",
        bridgeEnquiry: "After the catastrophe of WWII, did Britain and Italy learn the same lessons — or different ones?",
        bridgeConcept: "Democracy",
      },
    ],
  },
  9: {
    title: "Year 9",
    themes: [
      {
        id: "y9-sepoct",
        period: "September / October",
        british: {
          title: "Decolonisation and the End of Empire",
          enquiry: "Was decolonisation a triumph of self-determination or an unfinished project?",
          topics: ["The post-war decline of European empires", "Indian independence and partition", "African decolonisation", "The legacy of empire today"],
          skills: ["Causation", "Significance", "Interpretations", "Contemporary connections"],
          knowledge: ["Indian independence and partition 1947", "The Suez Crisis 1956", "Kenyan Mau Mau uprising", "The Commonwealth"],
          assessment: "Extended essay: Was decolonisation successful?",
          concepts: ["Independence", "Self-determination", "Legacy"],
          vocab: { en: ["decolonisation", "self-determination", "partition", "neo-colonialism", "commonwealth"], it: ["decolonizzazione", "autodeterminazione", "partizione", "neo-colonialismo", "commonwealth"] },
          access: "Case study comparison",
          stretch: "Argue whether 'neo-colonialism' is a meaningful concept or an excuse for post-independence failures",
        },
        italian: {
          title: "La decolonizzazione e l'eredità dell'impero italiano",
          enquiry: "Come l'Italia ha affrontato (o evitato) i conti con il suo passato coloniale?",
          topics: ["La fine dell'impero italiano", "L'Eritrea, la Libia e la Somalia nel dopoguerra", "La memoria coloniale in Italia", "Confronto con la decolonizzazione europea"],
          skills: ["Causalità", "Significato", "Interpretazioni", "Connessioni contemporanee"],
          knowledge: ["La perdita delle colonie dopo il 1943", "Il dibattito sulla memoria coloniale in Italia", "I monumenti e la rimozione della storia coloniale", "L'immigrazione post-coloniale"],
          assessment: "Saggio esteso: L'Italia ha fatto i conti con il suo passato coloniale?",
          concepts: ["Indipendenza", "Autodeterminazione", "Eredità"],
          vocab: { en: ["colonial memory", "reconciliation", "post-colonialism", "migration"], it: ["memoria coloniale", "riconciliazione", "post-colonialismo", "migrazione"] },
          access: "Confronto di casi di studio",
          stretch: "Confrontare come diversi paesi europei hanno gestito (o non gestito) la memoria coloniale",
        },
        crossStream: "Both streams examine decolonisation but Britain is the empire being dismantled while Italy must confront a less well-known colonial history — smaller in scale but equally significant morally.",
        bridgeEnquiry: "Does it matter how large an empire was when accounting for its moral and historical legacy?",
        bridgeConcept: "Legacy",
      },
      {
        id: "y9-novdecjan",
        period: "November / December / January",
        british: {
          title: "The Holocaust",
          enquiry: "How was the Holocaust possible in a modern, civilised society?",
          topics: ["The origins of Nazi antisemitism", "The escalation from persecution to genocide", "The world's response (and failure to respond)", "Memory, testimony, and responsibility"],
          skills: ["Moral reasoning", "Source analysis (testimony)", "Significance", "Ethical questioning"],
          knowledge: ["Nuremberg Laws 1935", "Kristallnacht 1938", "The Wannsee Conference 1942", "Liberation of the camps 1945", "The Nuremberg Trials"],
          assessment: "Extended analytical essay: How was the Holocaust possible?",
          concepts: ["Genocide", "Responsibility", "Memory"],
          vocab: { en: ["antisemitism", "genocide", "perpetrator", "bystander", "testimony"], it: ["antisemitismo", "genocidio", "perpetratore", "spettatore", "testimonianza"] },
          access: "Structured empathy and analysis framework",
          stretch: "Engage with the Milgram experiments and Arendt's 'banality of evil' — how far do they explain perpetrator behaviour?",
        },
        italian: {
          title: "La Shoah in Italia",
          enquiry: "Come il fascismo italiano portò alla persecuzione degli ebrei italiani?",
          topics: ["Le leggi razziali del 1938", "La Shoah in Italia dopo il 1943", "Gli italiani di fronte alla persecuzione: aiutatori, collaboratori, spettatori", "La memoria della Shoah in Italia"],
          skills: ["Ragionamento morale", "Analisi di fonti (testimonianze)", "Significato", "Questioni etiche"],
          knowledge: ["Le leggi razziali del 1938", "L'occupazione tedesca e le deportazioni", "Il Giorno della Memoria in Italia", "Primo Levi e la letteratura della Shoah"],
          assessment: "Saggio analitico esteso: Come il fascismo italiano portò alla persecuzione degli ebrei?",
          concepts: ["Genocidio", "Responsabilità", "Memoria"],
          vocab: { en: ["racial laws", "deportation", "Primo Levi", "memory"], it: ["leggi razziali", "deportazione", "Primo Levi", "memoria"] },
          access: "Struttura per analisi ed empatia",
          stretch: "Analizzare le testimonianze di Primo Levi e valutare come la letteratura può essere fonte storica",
        },
        crossStream: "The Holocaust is studied from both national perspectives: Britain as an outside observer (and reluctant rescuer), Italy as a fascist state that enacted racial laws and participated in deportations.",
        bridgeEnquiry: "When a state commits atrocities, who bears responsibility — the leaders, the followers, the bystanders, or all of us?",
        bridgeConcept: "Responsibility",
      },
      {
        id: "y9-febmar",
        period: "February / March",
        british: {
          title: "The Civil Rights Movement",
          enquiry: "How far had civil rights been achieved in America by 1968 — and at what cost?",
          topics: ["Segregation and Jim Crow", "Martin Luther King and non-violent protest", "Malcolm X and Black Power", "The legacy of the Civil Rights Movement"],
          skills: ["Causation", "Significance", "Interpretations", "Comparing approaches"],
          knowledge: ["Brown v Board of Education 1954", "Montgomery Bus Boycott 1955", "The March on Washington 1963", "Civil Rights Act 1964", "Assassination of MLK 1968"],
          assessment: "Essay: How significant were the achievements of the Civil Rights Movement by 1968?",
          concepts: ["Rights", "Equality", "Protest"],
          vocab: { en: ["segregation", "civil rights", "non-violence", "black power", "equality"], it: ["segregazione", "diritti civili", "non-violenza", "black power", "uguaglianza"] },
          access: "Timeline and significance ranking",
          stretch: "Compare the tactics of MLK and Malcolm X — which approach was more effective, and by what measure?",
        },
        italian: {
          title: "I movimenti per i diritti civili nel mondo",
          enquiry: "I movimenti per i diritti civili del Novecento cambiarono davvero la storia?",
          topics: ["Il movimento per i diritti civili negli USA", "I movimenti studenteschi del 1968 in Europa", "Il '68 in Italia", "Gandhi e la non-violenza"],
          skills: ["Causalità", "Significato", "Interpretazioni", "Confronto di approcci"],
          knowledge: ["Martin Luther King e il movimento per i diritti civili", "Il Sessantotto italiano", "Gandhi e la resistenza non violenta", "Il femminismo e i nuovi movimenti sociali"],
          assessment: "Saggio: I movimenti del Sessantotto cambiarono davvero la storia?",
          concepts: ["Diritti", "Uguaglianza", "Protesta"],
          vocab: { en: ["protest", "1968", "feminism", "social movement"], it: ["protesta", "1968", "femminismo", "movimento sociale"] },
          access: "Timeline e classificazione per importanza",
          stretch: "Confrontare i movimenti del Sessantotto nei diversi paesi — cosa ebbero in comune e cosa li distinse?",
        },
        crossStream: "Both streams study protest movements but the Italian stream places the US Civil Rights Movement in a global context of 1968 and connects it to Italian student movements.",
        bridgeEnquiry: "Why did so many different countries experience social upheaval at the same time in 1968 — is there such a thing as a global historical moment?",
        bridgeConcept: "Protest",
      },
      {
        id: "y9-marapr",
        period: "March / April",
        british: {
          title: "Britain in the Modern World",
          enquiry: "What does it mean to be British in the 21st century?",
          topics: ["Immigration and multiculturalism", "Britain and the EU (Brexit)", "Devolution and national identity", "Britain's place in a post-imperial world"],
          skills: ["Contemporary connections", "Interpretations", "Significance", "Identity analysis"],
          knowledge: ["Windrush generation", "The Good Friday Agreement 1998", "Devolution in Scotland and Wales", "Brexit referendum 2016"],
          assessment: "Analytical essay: How has British identity changed since 1945?",
          concepts: ["Identity", "Belonging", "Nation"],
          vocab: { en: ["multiculturalism", "devolution", "Brexit", "national identity", "belonging"], it: ["multiculturalismo", "devoluzione", "Brexit", "identità nazionale", "appartenenza"] },
          access: "Identity concept map",
          stretch: "Construct a sophisticated argument: is 'British identity' a coherent concept in 2024?",
        },
        italian: {
          title: "L'Italia contemporanea e l'identità italiana",
          enquiry: "Cosa significa essere italiani nel XXI secolo?",
          topics: ["L'immigrazione e la società multiculturale", "L'Italia nell'Unione Europea", "Il populismo e la crisi della democrazia", "L'identità italiana nel mondo globalizzato"],
          skills: ["Connessioni contemporanee", "Interpretazioni", "Significato", "Analisi dell'identità"],
          knowledge: ["L'immigrazione in Italia dagli anni '90", "L'Italia e l'euro", "Berlusconi e il populismo italiano", "L'identità regionale contro quella nazionale"],
          assessment: "Saggio analitico: Come è cambiata l'identità italiana dal 1945 ad oggi?",
          concepts: ["Identità", "Appartenenza", "Nazione"],
          vocab: { en: ["populism", "European Union", "immigration", "regional identity"], it: ["populismo", "Unione Europea", "immigrazione", "identità regionale"] },
          access: "Mappa concettuale sull'identità",
          stretch: "L'identità italiana è definita dalla nazione o dalla regione, dalla cultura o dalla lingua? Costruire un argomento articolato.",
        },
        crossStream: "Both countries grapple with post-imperial identity in an age of globalisation. Britain's Brexit and Italy's populism are different responses to similar anxieties about belonging and sovereignty.",
        bridgeEnquiry: "Do Britain and Italy share the same anxieties about identity and belonging in the 21st century, even though they express them differently?",
        bridgeConcept: "Identity",
      },
      {
        id: "y9-aprmay",
        period: "April / May",
        british: {
          title: "Globalisation and its Discontents",
          enquiry: "Has globalisation made the world more equal or more divided?",
          topics: ["What is globalisation?", "Winners and losers of globalisation", "Climate change as a global historical problem", "The future of global cooperation"],
          skills: ["Contemporary connections", "Statistical analysis", "Argument construction"],
          knowledge: ["Global supply chains", "The 2008 financial crisis", "Paris Agreement 2015", "Rise of China"],
          assessment: "Structured debate essay: Has globalisation been good for the world?",
          concepts: ["Globalisation", "Inequality", "Cooperation"],
          vocab: { en: ["globalisation", "inequality", "climate", "cooperation", "sovereignty"], it: ["globalizzazione", "disuguaglianza", "clima", "cooperazione", "sovranità"] },
          access: "Winners and losers sorting activity",
          stretch: "Construct a nuanced argument that avoids both uncritical celebration and uncritical rejection of globalisation",
        },
        italian: {
          title: "La globalizzazione e le sue sfide",
          enquiry: "La globalizzazione ha reso il mondo più giusto o più disuguale?",
          topics: ["Che cos'è la globalizzazione?", "Vincitori e perdenti della globalizzazione", "Il cambiamento climatico come problema storico globale", "Il futuro della cooperazione internazionale"],
          skills: ["Connessioni contemporanee", "Analisi statistica", "Costruzione di argomenti"],
          knowledge: ["Le catene di produzione globali", "La crisi finanziaria del 2008", "L'Accordo di Parigi 2015", "L'ascesa della Cina"],
          assessment: "Saggio dibattito: La globalizzazione ha fatto bene al mondo?",
          concepts: ["Globalizzazione", "Disuguaglianza", "Cooperazione"],
          vocab: { en: ["globalisation", "inequality", "climate", "cooperation"], it: ["globalizzazione", "disuguaglianza", "clima", "cooperazione"] },
          access: "Attività di classificazione: vincitori e perdenti",
          stretch: "Costruire un argomento articolato che eviti sia la celebrazione acritica che il rifiuto totale della globalizzazione",
        },
        crossStream: "Both streams study the same contemporary challenge with the same core questions, though using different national examples and connecting to different national histories.",
        bridgeEnquiry: "In a globalised world, does it still make sense to study history through a national lens — or do we need new frameworks?",
        bridgeConcept: "Cooperation",
      },
      {
        id: "y9-jun",
        period: "June",
        british: {
          title: "Historical Thinking — Synoptic Reflection",
          enquiry: "What have we learned about how history works over three years?",
          topics: ["Revisiting key concepts: causation, significance, change", "How historians write and revise history", "The uses and abuses of history", "What history is for"],
          skills: ["Metacognition", "Synthesis", "Extended argument", "Reflection"],
          knowledge: ["Key events and themes from Years 7-9", "How historical interpretations change", "The role of history in civic life"],
          assessment: "Synoptic end-of-year project: Choose one turning point from any year and argue for its significance",
          concepts: ["Memory", "Significance", "Truth"],
          vocab: { en: ["historiography", "interpretation", "synthesis", "legacy", "significance"], it: ["storiografia", "interpretazione", "sintesi", "eredità", "significato"] },
          access: "Guided reflection framework",
          stretch: "Write a historiographical essay arguing that one key event has been consistently misinterpreted",
        },
        italian: {
          title: "Il pensiero storico — riflessione sinottica",
          enquiry: "Cosa abbiamo imparato su come funziona la storia in tre anni?",
          topics: ["Revisione dei concetti chiave: causalità, significato, cambiamento", "Come gli storici scrivono e riscrivono la storia", "Gli usi e gli abusi della storia", "A cosa serve la storia"],
          skills: ["Metacognizione", "Sintesi", "Argomento esteso", "Riflessione"],
          knowledge: ["Temi chiave degli anni 7-9", "Come cambiano le interpretazioni storiche", "Il ruolo della storia nella vita civica"],
          assessment: "Progetto sinottico di fine anno: Scegli un punto di svolta da qualsiasi anno e argomenta la sua importanza",
          concepts: ["Memoria", "Significato", "Verità"],
          vocab: { en: ["historiography", "interpretation", "synthesis"], it: ["storiografia", "interpretazione", "sintesi"] },
          access: "Schema di riflessione guidata",
          stretch: "Scrivere un saggio storiografico che argomenta che un evento chiave è stato costantemente frainteso",
        },
        crossStream: "The final unit is a shared metacognitive reflection across both streams — students from both cohorts are encouraged to synthesise their three-year journey together.",
        bridgeEnquiry: "After three years of studying British and Italian history in parallel, what have you learned about how different national stories relate to a shared human story?",
        bridgeConcept: "Memory",
      },
    ],
  },
};

export const MONTHS = [
  "September","October","November","December",
  "January","February","March","April","May","June",
];

export function periodIncludes(period, month) {
  return period.split(" / ").includes(month);
}

export function getThemesByMonth(yearId, month) {
  const year = CURRICULUM[yearId];
  if (!year) return [];
  return year.themes.filter((t) => periodIncludes(t.period, month));
}
